// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: questionnaire.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Types int32

const (
	Types_RADIO    Types = 0
	Types_CHECKBOX Types = 1
	Types_TEXT     Types = 2
)

// Enum value maps for Types.
var (
	Types_name = map[int32]string{
		0: "RADIO",
		1: "CHECKBOX",
		2: "TEXT",
	}
	Types_value = map[string]int32{
		"RADIO":    0,
		"CHECKBOX": 1,
		"TEXT":     2,
	}
)

func (x Types) Enum() *Types {
	p := new(Types)
	*p = x
	return p
}

func (x Types) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Types) Descriptor() protoreflect.EnumDescriptor {
	return file_questionnaire_proto_enumTypes[0].Descriptor()
}

func (Types) Type() protoreflect.EnumType {
	return &file_questionnaire_proto_enumTypes[0]
}

func (x Types) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Types.Descriptor instead.
func (Types) EnumDescriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{0}
}

type CreateQuestionnaireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questionnaire *Questionnaire `protobuf:"bytes,1,opt,name=questionnaire,proto3" json:"questionnaire,omitempty"`
}

func (x *CreateQuestionnaireRequest) Reset() {
	*x = CreateQuestionnaireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQuestionnaireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionnaireRequest) ProtoMessage() {}

func (x *CreateQuestionnaireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionnaireRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionnaireRequest) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQuestionnaireRequest) GetQuestionnaire() *Questionnaire {
	if x != nil {
		return x.Questionnaire
	}
	return nil
}

type CreateQuestionnaireResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref   string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateQuestionnaireResponse) Reset() {
	*x = CreateQuestionnaireResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateQuestionnaireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionnaireResponse) ProtoMessage() {}

func (x *CreateQuestionnaireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionnaireResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionnaireResponse) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{1}
}

func (x *CreateQuestionnaireResponse) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *CreateQuestionnaireResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetQuestionnaireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *GetQuestionnaireRequest) Reset() {
	*x = GetQuestionnaireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionnaireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnaireRequest) ProtoMessage() {}

func (x *GetQuestionnaireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnaireRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionnaireRequest) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuestionnaireRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type GetQuestionnaireResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questionnaire *Questionnaire `protobuf:"bytes,1,opt,name=questionnaire,proto3" json:"questionnaire,omitempty"`
	Error         *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetQuestionnaireResponse) Reset() {
	*x = GetQuestionnaireResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuestionnaireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionnaireResponse) ProtoMessage() {}

func (x *GetQuestionnaireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionnaireResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionnaireResponse) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuestionnaireResponse) GetQuestionnaire() *Questionnaire {
	if x != nil {
		return x.Questionnaire
	}
	return nil
}

func (x *GetQuestionnaireResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateQuestionnaireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questionnaire *Questionnaire `protobuf:"bytes,1,opt,name=questionnaire,proto3" json:"questionnaire,omitempty"`
}

func (x *UpdateQuestionnaireRequest) Reset() {
	*x = UpdateQuestionnaireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQuestionnaireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionnaireRequest) ProtoMessage() {}

func (x *UpdateQuestionnaireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionnaireRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionnaireRequest) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateQuestionnaireRequest) GetQuestionnaire() *Questionnaire {
	if x != nil {
		return x.Questionnaire
	}
	return nil
}

type UpdateQuestionnaireResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateQuestionnaireResponse) Reset() {
	*x = UpdateQuestionnaireResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQuestionnaireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionnaireResponse) ProtoMessage() {}

func (x *UpdateQuestionnaireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionnaireResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionnaireResponse) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateQuestionnaireResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteQuestionnaireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *DeleteQuestionnaireRequest) Reset() {
	*x = DeleteQuestionnaireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteQuestionnaireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionnaireRequest) ProtoMessage() {}

func (x *DeleteQuestionnaireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionnaireRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionnaireRequest) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteQuestionnaireRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type Questionnaire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Ref       string      `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Questions []*Question `protobuf:"bytes,4,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *Questionnaire) Reset() {
	*x = Questionnaire{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Questionnaire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Questionnaire) ProtoMessage() {}

func (x *Questionnaire) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Questionnaire.ProtoReflect.Descriptor instead.
func (*Questionnaire) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{7}
}

func (x *Questionnaire) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Questionnaire) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Questionnaire) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Questionnaire) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Statement string   `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
	Type      Types    `protobuf:"varint,3,opt,name=type,proto3,enum=proto.Types" json:"type,omitempty"`
	Options   []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{8}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *Question) GetType() Types {
	if x != nil {
		return x.Type
	}
	return Types_RADIO
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_questionnaire_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_questionnaire_proto protoreflect.FileDescriptor

var file_questionnaire_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x1a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61,
	0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69,
	0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x22, 0x53, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2b, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22, 0x7a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x6e, 0x61, 0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72,
	0x65, 0x52, 0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x58, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61,
	0x69, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52,
	0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x22, 0x41,
	0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x2e, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65,
	0x66, 0x22, 0x76, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69,
	0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x2d, 0x0a, 0x09, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x74, 0x0a, 0x08, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x2f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x2a, 0x2a, 0x0a, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x41, 0x44,
	0x49, 0x4f, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x42, 0x4f, 0x58,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x32, 0xad, 0x02, 0x0a,
	0x14, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x12, 0x21, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61,
	0x69, 0x72, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x6e, 0x61, 0x69,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_questionnaire_proto_rawDescOnce sync.Once
	file_questionnaire_proto_rawDescData = file_questionnaire_proto_rawDesc
)

func file_questionnaire_proto_rawDescGZIP() []byte {
	file_questionnaire_proto_rawDescOnce.Do(func() {
		file_questionnaire_proto_rawDescData = protoimpl.X.CompressGZIP(file_questionnaire_proto_rawDescData)
	})
	return file_questionnaire_proto_rawDescData
}

var file_questionnaire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_questionnaire_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_questionnaire_proto_goTypes = []interface{}{
	(Types)(0),                          // 0: proto.Types
	(*CreateQuestionnaireRequest)(nil),  // 1: proto.CreateQuestionnaireRequest
	(*CreateQuestionnaireResponse)(nil), // 2: proto.CreateQuestionnaireResponse
	(*GetQuestionnaireRequest)(nil),     // 3: proto.GetQuestionnaireRequest
	(*GetQuestionnaireResponse)(nil),    // 4: proto.GetQuestionnaireResponse
	(*UpdateQuestionnaireRequest)(nil),  // 5: proto.UpdateQuestionnaireRequest
	(*UpdateQuestionnaireResponse)(nil), // 6: proto.UpdateQuestionnaireResponse
	(*DeleteQuestionnaireRequest)(nil),  // 7: proto.DeleteQuestionnaireRequest
	(*Questionnaire)(nil),               // 8: proto.Questionnaire
	(*Question)(nil),                    // 9: proto.Question
	(*Error)(nil),                       // 10: proto.Error
}
var file_questionnaire_proto_depIdxs = []int32{
	8,  // 0: proto.CreateQuestionnaireRequest.questionnaire:type_name -> proto.Questionnaire
	10, // 1: proto.CreateQuestionnaireResponse.error:type_name -> proto.Error
	8,  // 2: proto.GetQuestionnaireResponse.questionnaire:type_name -> proto.Questionnaire
	10, // 3: proto.GetQuestionnaireResponse.error:type_name -> proto.Error
	8,  // 4: proto.UpdateQuestionnaireRequest.questionnaire:type_name -> proto.Questionnaire
	10, // 5: proto.UpdateQuestionnaireResponse.error:type_name -> proto.Error
	9,  // 6: proto.Questionnaire.questions:type_name -> proto.Question
	0,  // 7: proto.Question.type:type_name -> proto.Types
	1,  // 8: proto.QuestionnaireService.CreateQuestionnaire:input_type -> proto.CreateQuestionnaireRequest
	3,  // 9: proto.QuestionnaireService.GetQuestionnaire:input_type -> proto.GetQuestionnaireRequest
	5,  // 10: proto.QuestionnaireService.UpdateQuestionnaire:input_type -> proto.UpdateQuestionnaireRequest
	2,  // 11: proto.QuestionnaireService.CreateQuestionnaire:output_type -> proto.CreateQuestionnaireResponse
	4,  // 12: proto.QuestionnaireService.GetQuestionnaire:output_type -> proto.GetQuestionnaireResponse
	6,  // 13: proto.QuestionnaireService.UpdateQuestionnaire:output_type -> proto.UpdateQuestionnaireResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_questionnaire_proto_init() }
func file_questionnaire_proto_init() {
	if File_questionnaire_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_questionnaire_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQuestionnaireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateQuestionnaireResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionnaireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuestionnaireResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQuestionnaireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQuestionnaireResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteQuestionnaireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Questionnaire); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_questionnaire_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_questionnaire_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_questionnaire_proto_goTypes,
		DependencyIndexes: file_questionnaire_proto_depIdxs,
		EnumInfos:         file_questionnaire_proto_enumTypes,
		MessageInfos:      file_questionnaire_proto_msgTypes,
	}.Build()
	File_questionnaire_proto = out.File
	file_questionnaire_proto_rawDesc = nil
	file_questionnaire_proto_goTypes = nil
	file_questionnaire_proto_depIdxs = nil
}
